// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { registerControllers } from "stimulus-vite-helpers"
import { application } from "./application"

const controllers = import.meta.globEager('./**/*_controller.js')
registerControllers(application, controllers)
